"""Place the existing power stage using KiCad 9's pcbnew geometry API.

Run with KiCad's bundled python.exe. Only listed footprint blocks are replaced;
the Pico, LCD connector, mounting holes, keepouts and board drawing stay verbatim.
No traces, components or electrical connections are generated by this script.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import tempfile
from pathlib import Path

import pcbnew

ROOT = Path(__file__).resolve().parent
BOARD = ROOT / "pico_lta042b010f_carrier.kicad_pcb"
# Coordinates in mm, KiCad rotation in degrees; each origin is the real footprint
# origin (usually pad 1 for THT). Electrical component values remain unchanged.
PLACEMENT = {
    "J2": (17.7, 28.0, 90), "J3": (2.25, 38.75, 180),
    "U3": (23.0, 22.25, 90), "L1": (20.03, 41.3, 90),
    "C6": (10.25, 37.0, 270), "R7": (22.25, 11.75, 270),
    "R8": (4.75, 8.75, 0), "D4": (16.5, 32.5, 0),
    "C8": (23.75, 32.25, 90), "C7": (13.25, 32.5, 180),
    "R9": (15.75, 8.25, 0), "R10": (23.25, 8.0, 180),
    "C9": (11.25, 6.0, 270), "D6": (4.75, 32.5, 0),
    "D7": (13.0, 2.25, 180), "C11": (18.5, 3.5, 180),
    "R11": (24.75, 50.0, 180), "D5": (22.75, 2.5, 270),
    "R16": (4.25, 42.75, 180), "D8": (10.0, 47.0, 90),
    "R17": (13.5, 46.75, 90), "R18": (24.0, 27.25, 180),
    "TP1": (9.5, 50.0, 90), "TP2": (12.75, 50.0, 90),
    "TP3": (16.0, 50.0, 90), "TP4": (19.25, 50.0, 90),
}

REGION = (0.4, 0.4, 26.6, 51.6)
TOP_NOTCH = (25.0, 0.0, 26.6, 10.0)
FIXED_REFERENCES = ("J1", "H1", "H2")
CLEARANCE = 0.15


def place_reference_fields(board):
    """Keep dense power-stage references on fabrication, not crowded silkscreen."""
    footprints = {f.GetReference(): f for f in board.GetFootprints()}
    for ref in PLACEMENT:
        footprint = footprints[ref]
        field = footprint.Reference()
        field.SetLayer(pcbnew.F_Fab)
        field.SetPosition(footprint.GetPosition())
        field.SetTextAngle(pcbnew.EDA_ANGLE(0, pcbnew.DEGREES_T))
        field.SetTextSize(
            pcbnew.VECTOR2I(pcbnew.FromMM(0.8), pcbnew.FromMM(0.8))
        )


def place_diode_polarity_markers(board):
    """Keep crowded vertical-diode cathode marks on fabrication only."""
    footprints = {f.GetReference(): f for f in board.GetFootprints()}
    for ref in ("D4", "D7"):
        for item in footprints[ref].GraphicalItems():
            if (
                isinstance(item, pcbnew.PCB_TEXT)
                and item.GetLayer() == pcbnew.F_SilkS
                and item.GetText() == "K"
            ):
                item.SetLayer(pcbnew.F_Fab)


def validate_red_zone(board):
    """Prove target courtyards stay inside the marked red area and do not overlap."""
    layers = pcbnew.LSET()
    layers.AddLayer(pcbnew.F_CrtYd)
    footprints = {f.GetReference(): f for f in board.GetFootprints()}

    def bounds(ref):
        item = footprints[ref]
        rect = item.GetLayerBoundingBox(layers)
        if rect.GetWidth() <= 0 or rect.GetHeight() <= 0:
            rect = item.GetBoundingBox(False, False)
        return tuple(pcbnew.ToMM(v) for v in
                     (rect.GetX(), rect.GetY(), rect.GetRight(), rect.GetBottom()))

    def overlap(a, b, gap=0.0):
        return (min(a[2], b[2]) - max(a[0], b[0]) + gap > 0
                and min(a[3], b[3]) - max(a[1], b[1]) + gap > 0)

    boxes = {ref: bounds(ref) for ref in PLACEMENT}
    errors = []
    for ref, box in boxes.items():
        if (box[0] < REGION[0] or box[1] < REGION[1]
                or box[2] > REGION[2] or box[3] > REGION[3]):
            errors.append(f"{ref} courtyard outside red zone: {box}")
        if overlap(box, TOP_NOTCH):
            errors.append(f"{ref} courtyard overlaps top board cutout: {box}")
    refs = list(boxes)
    for index, ref in enumerate(refs):
        for other in refs[index + 1:]:
            if overlap(boxes[ref], boxes[other], CLEARANCE):
                errors.append(f"{ref}/{other} courtyards overlap")
        for fixed in FIXED_REFERENCES:
            if overlap(boxes[ref], bounds(fixed), CLEARANCE):
                errors.append(f"{ref}/{fixed} courtyards overlap")
    j2 = boxes["J2"]
    if abs(j2[0] - REGION[0]) > 0.11:
        errors.append(f"J2 USB opening is not aligned to the left perimeter: {j2}")
    j3 = boxes["J3"]
    j3_inset = min(
        j3[0] - REGION[0], REGION[2] - j3[2],
        j3[1] - REGION[1], REGION[3] - j3[3],
    )
    if j3_inset > 0.25:
        errors.append(f"J3 is not on the red-zone perimeter: {j3}")
    tp_boxes = [boxes[f"TP{index}"] for index in range(1, 5)]
    if max(box[3] for box in tp_boxes) - min(box[3] for box in tp_boxes) > 0.25:
        errors.append("TP1-TP4 are not aligned as one perimeter group")
    if max(REGION[3] - box[3] for box in tp_boxes) > 0.25:
        errors.append("TP1-TP4 are not on the bottom perimeter")
    if max(box[2] for box in tp_boxes) - min(box[0] for box in tp_boxes) > 14.5:
        errors.append("TP1-TP4 are not sufficiently grouped")
    if errors:
        raise AssertionError("Red-zone validation failed:\n" + "\n".join(errors))
    return boxes


def children(text):
    """Span-aware S-expression scanner; quotes and nested coordinates are safe."""
    depth, quoted, escaped, start = 0, False, False, 0
    for i, ch in enumerate(text):
        if quoted:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                quoted = False
        elif ch == '"':
            quoted = True
        elif ch == "(":
            depth += 1
            if depth == 2:
                start = i
        elif ch == ")":
            if depth == 2:
                yield start, i + 1, text[start:i + 1]
            depth -= 1
    if depth or quoted:
        raise ValueError("Unbalanced KiCad file")


def footprint_blocks(text):
    result = {}
    for start, end, block in children(text):
        if block.startswith("(footprint "):
            match = re.search(r'\(property "Reference" "([^"]+)"', block)
            if not match or match[1] in result:
                raise ValueError("Missing or duplicate footprint reference")
            result[match[1]] = (start, end, block)
    return result


def signature(board):
    return sorted((f.GetReference(), f.GetValue(), f.GetFPIDAsString(),
                   sorted((p.GetNumber(), p.GetNetname(),
                           p.GetDrillSize().x, p.GetDrillSize().y,
                           p.GetSize().x, p.GetSize().y) for p in f.Pads()))
                  for f in board.GetFootprints())


def xy(point):
    return (pcbnew.ToMM(point.x), pcbnew.ToMM(point.y))


def measurements(board):
    fp = {f.GetReference(): f for f in board.GetFootprints()}
    def p(ref, pin):
        return xy(next(p for p in fp[ref].Pads() if p.GetNumber() == pin).GetPosition())
    def distance(a, b):
        return math.dist(p(*a), p(*b))
    links = {
        "switch_to_diode": (("U3", "1"), ("D4", "2")),
        "diode_to_output_cap": (("D4", "1"), ("C8", "1")),
        "output_cap_to_switch_ground": (("C8", "2"), ("U3", "2")),
        "inductor_to_switch": (("L1", "2"), ("U3", "1")),
        "sense_to_pin7": (("R7", "2"), ("U3", "7")),
        "input_cap_to_vin": (("C6", "1"), ("U3", "6")),
        "input_cap_to_ground": (("C6", "2"), ("U3", "2")),
        "timing_to_pin3": (("C7", "1"), ("U3", "3")),
        "feedback_upper_to_pin5": (("R9", "2"), ("U3", "5")),
        "feedback_lower_to_pin5": (("R10", "1"), ("U3", "5")),
        "charge_cap_to_clamp": (("C9", "2"), ("D6", "2")),
        "charge_cap_to_rectifier": (("C9", "2"), ("D7", "2")),
        "switch_to_charge_cap": (("U3", "1"), ("C9", "1")),
    }
    return {name: round(distance(*link), 3) for name, link in links.items()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=BOARD)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    parser.add_argument("--placement-json", type=Path)
    args = parser.parse_args()
    if args.placement_json:
        overrides = json.loads(args.placement_json.read_text(encoding="utf-8"))
        if not overrides.keys() <= PLACEMENT.keys():
            raise ValueError("Unexpected reference in placement override")
        PLACEMENT.update(overrides)
    before_bytes = args.input.read_bytes()
    before = before_bytes.decode("utf-8")
    source = footprint_blocks(before)
    board = pcbnew.LoadBoard(str(args.input))
    before_signature = signature(board)
    before_measurements = measurements(board)
    fp = {f.GetReference(): f for f in board.GetFootprints()}
    if len(board.GetTracks()):
        raise ValueError("Placement-only input required; existing traces must be handled explicitly")
    if not set(PLACEMENT) <= fp.keys():
        raise ValueError("Missing target footprint")
    for ref, (x, y, angle) in PLACEMENT.items():
        item = fp[ref]
        item.SetOrientationDegrees(angle)
        item.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(x), pcbnew.FromMM(y)))
        # A rotated footprint's text orientation is global in pcbnew, not local.
        text = item.Reference()
        text.SetTextAngle(pcbnew.EDA_ANGLE(0, pcbnew.DEGREES_T))
        text.SetTextSize(pcbnew.VECTOR2I(pcbnew.FromMM(0.85), pcbnew.FromMM(0.85)))
        text.SetTextThickness(pcbnew.FromMM(0.13))
    place_reference_fields(board)
    place_diode_polarity_markers(board)
    # Legacy block-divider silk lines and off-board draft notes describe the old
    # placement. Retain them as editable drawing annotations, not printed silk.
    changed_graphics = set()
    note_index = 0
    for drawing in board.GetDrawings():
        if drawing.GetLayer() != pcbnew.F_SilkS:
            continue
        if isinstance(drawing, pcbnew.PCB_TEXT):
            drawing.SetLayer(pcbnew.Dwgs_User)
            drawing.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(50), pcbnew.FromMM(13 + 2*note_index)))
            drawing.SetTextAngle(pcbnew.EDA_ANGLE(0, pcbnew.DEGREES_T))
            drawing.SetTextSize(pcbnew.VECTOR2I(pcbnew.FromMM(0.6), pcbnew.FromMM(0.6)))
            note_index += 1
            changed_graphics.add(drawing.m_Uuid.AsString())
        elif isinstance(drawing, pcbnew.PCB_SHAPE):
            drawing.SetLayer(pcbnew.Dwgs_User)
            changed_graphics.add(drawing.m_Uuid.AsString())
    def graphic_id(block):
        if not re.match(r'\(gr_(?:text|line)\b', block):
            return None
        match = re.search(r'\(uuid "([^"]+)"\)', block)
        return match[1] if match else None
    if signature(board) != before_signature:
        raise AssertionError("Placement altered electrical or footprint identity")
    with tempfile.TemporaryDirectory(prefix="pico-power-place-") as tmp:
        normal = Path(tmp) / "native.kicad_pcb"
        pcbnew.SaveBoard(str(normal), board)
        native_text = normal.read_text(encoding="utf-8")
        # Match the input's newline convention without Windows text-mode
        # translation, which would turn retained CRLF into CRCRLF.
        if "\r\n" in before:
            native_text = native_text.replace("\n", "\r\n")
        generated = footprint_blocks(native_text)
    after = before
    replacements = []
    for ref in PLACEMENT:
        start, end, _ = source[ref]
        replacements.append((start, end, generated[ref][2]))
    native_graphics = {graphic_id(block): block for _, _, block in children(native_text)
                       if graphic_id(block) in changed_graphics}
    for start, end, block in children(before):
        if graphic_id(block) in changed_graphics:
            replacements.append((start, end, native_graphics[graphic_id(block)]))
    for start, end, replacement in sorted(replacements, reverse=True):
        after = after[:start] + replacement + after[end:]
    result = footprint_blocks(after)
    for ref in source.keys() - PLACEMENT.keys():
        if source[ref][2] != result[ref][2]:
            raise AssertionError(f"Unrelated footprint modified: {ref}")
    untouched_before = [b for _, _, b in children(before) if not b.startswith("(footprint ") and graphic_id(b) not in changed_graphics]
    untouched_after = [b for _, _, b in children(after) if not b.startswith("(footprint ") and graphic_id(b) not in changed_graphics]
    if untouched_before != untouched_after:
        raise AssertionError("Board drawing, track, zone or keepout was modified")
    if args.input.read_bytes() != before_bytes:
        raise RuntimeError("Input was edited during placement; refusing to overwrite")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(after.encode("utf-8"))
    reloaded = pcbnew.LoadBoard(str(args.output))
    if signature(reloaded) != before_signature:
        raise AssertionError("Reloaded PCB electrical signature mismatch")
    red_zone_bounds = validate_red_zone(reloaded)
    report = {
        "input_sha256": hashlib.sha256(before_bytes).hexdigest(),
        "footprints_moved": sorted(PLACEMENT),
        "electrical_signature_unchanged": True,
        "other_footprints_edges_keepouts_and_nets_verbatim": True,
        "all_target_courtyards_inside_red_zone": True,
        "target_courtyard_overlap_count": 0,
        "red_zone_mm": REGION,
        "top_board_cutout_mm": TOP_NOTCH,
        "target_courtyard_bounds_mm": red_zone_bounds,
        "draft_annotations_moved_to_Dwgs_User": len(changed_graphics),
        "before_pad_distances_mm": before_measurements,
        "after_pad_distances_mm": measurements(reloaded),
        "placements_mm_degrees": PLACEMENT,
        "note": "Distances are straight-line pad distances, not routed lengths or measured EMI.",
    }
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
