"""Place the existing power stage using KiCad 9's pcbnew geometry API.

Run with KiCad's bundled python.exe. Only listed footprint blocks are replaced;
the Pico, LCD connector, mounting holes, keepouts and board drawing stay verbatim.
No traces, components or electrical connections are generated by this script.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import tempfile
from pathlib import Path

import pcbnew

ROOT = Path(__file__).resolve().parent
BOARD = ROOT / "pico_lta042b010f_carrier.kicad_pcb"
# Coordinates in mm, KiCad rotation in degrees; each origin is the real footprint
# origin (usually pad 1 for THT). Electrical component values remain unchanged.
PLACEMENT = {
    "J2": (11.25, 2.25, 90), "J3": (22.25, 35.5, 90),
    "U3": (11.5, 32.75, 90), "L1": (18.0, 46.0, 180),
    "C6": (17.25, 18.5, 90), "R7": (2.5, 41.5, 90),
    "R8": (18.75, 23.5, 180), "D4": (9.25, 49.25, 90),
    "C8": (16.25, 28.5, 0), "C7": (5.75, 39.25, 270),
    "R9": (21.75, 22.25, 270), "R10": (14.0, 39.0, 0),
    "C9": (9.75, 22.5, 90), "D6": (2.0, 10.5, 0),
    "D7": (7.0, 36.0, 90), "C11": (18.25, 34.25, 180),
    "R11": (25.0, 22.25, 270), "D5": (2.75, 26.0, 270),
    "R16": (1.5, 14.25, 0), "D8": (5.25, 19.0, 180),
    "RV1": (14.75, 6.0, 0), "TP1": (24.75, 16.0, 90),
    "TP2": (23.0, 3.0, 90), "TP3": (10.5, 26.0, 90),
    "TP4": (9.5, 5.75, 90),
}

REGION = (0.4, 0.4, 26.6, 51.6)
TOP_NOTCH = (25.0, 0.0, 26.6, 10.0)
FIXED_REFERENCES = ("J1", "H1", "H2")
CLEARANCE = 0.15


def place_reference_fields(board):
    """Keep horizontal identifiers outside pad/body courtyards and other text."""
    layer = pcbnew.LSET()
    layer.AddLayer(pcbnew.F_CrtYd)
    fp = {f.GetReference(): f for f in board.GetFootprints()}
    def box(rect):
        return tuple(pcbnew.ToMM(v) for v in
                     (rect.GetX(), rect.GetY(), rect.GetRight(), rect.GetBottom()))
    body = {}
    for ref, f in fp.items():
        bounds = f.GetLayerBoundingBox(layer)
        if bounds.GetWidth() > 0 and bounds.GetHeight() > 0:
            body[ref] = box(bounds)
        else:
            objects = list(f.Pads()) + [g for g in f.GraphicalItems()
                                       if isinstance(g, pcbnew.PCB_SHAPE) and g.GetLayer() == pcbnew.F_SilkS]
            boxes = [box(g.GetBoundingBox()) for g in objects]
            body[ref] = (min(bb[0] for bb in boxes), min(bb[1] for bb in boxes),
                         max(bb[2] for bb in boxes), max(bb[3] for bb in boxes))
    placed = [box(f.Reference().GetBoundingBox()) for ref, f in fp.items() if ref not in PLACEMENT]
    crowded = ['U3', 'C7', 'R8', 'R10', 'R9', 'R7', 'D4', 'C6', 'C8']
    order = crowded + sorted(set(PLACEMENT) - set(crowded))
    def overlap(a, b):
        dx = min(a[2], b[2]) - max(a[0], b[0]) + 0.15
        dy = min(a[3], b[3]) - max(a[1], b[1]) + 0.15
        return max(dx, 0) * max(dy, 0)
    for ref in order:
        field = fp[ref].Reference()
        l, t, r, b = body[ref]
        cx, cy = (l+r)/2, (t+b)/2
        best = None
        for font in [0.85, 0.8]:
            field.SetTextSize(pcbnew.VECTOR2I(pcbnew.FromMM(font), pcbnew.FromMM(font)))
            field.SetTextAngle(pcbnew.EDA_ANGLE(0, pcbnew.DEGREES_T))
            width = len(ref) * font * 0.8
            for gap in [0.7, 1.1, 1.6, 2.2, 3.0]:
                candidates = [(cx, t-gap), (cx, b+gap), (l-gap-width/2, cy), (r+gap+width/2, cy)]
                for shift in [-2, 2]:
                    candidates += [(cx+shift,t-gap),(cx+shift,b+gap)]
                for x, y in candidates:
                    field.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(x), pcbnew.FromMM(y)))
                    bounds = box(field.GetBoundingBox())
                    outside = (max(REGION[0]-bounds[0], 0)
                               + max(bounds[2]-REGION[2], 0)
                               + max(REGION[1]-bounds[1], 0)
                               + max(bounds[3]-REGION[3], 0))
                    notch_dx = max(0, min(bounds[2], TOP_NOTCH[2])
                                   - max(bounds[0], TOP_NOTCH[0]))
                    notch_dy = max(0, min(bounds[3], TOP_NOTCH[3])
                                   - max(bounds[1], TOP_NOTCH[1]))
                    outside += 10 * notch_dx * notch_dy
                    penalty = 10000 * (outside + sum(overlap(bounds, bb) for bb in body.values()) + sum(overlap(bounds,bb) for bb in placed))
                    score = penalty + math.dist((x,y),(cx,cy)) + 8*(0.85-font)
                    if best is None or score < best[0]:
                        best = (score,x,y,font)
        _, x, y, font = best
        field.SetTextSize(pcbnew.VECTOR2I(pcbnew.FromMM(font),pcbnew.FromMM(font)))
        field.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(x),pcbnew.FromMM(y)))
        placed.append(box(field.GetBoundingBox()))


def validate_red_zone(board):
    """Prove target courtyards stay inside the marked red area and do not overlap."""
    layers = pcbnew.LSET()
    layers.AddLayer(pcbnew.F_CrtYd)
    footprints = {f.GetReference(): f for f in board.GetFootprints()}

    def bounds(ref):
        item = footprints[ref]
        rect = item.GetLayerBoundingBox(layers)
        if rect.GetWidth() <= 0 or rect.GetHeight() <= 0:
            rect = item.GetBoundingBox(False, False)
        return tuple(pcbnew.ToMM(v) for v in
                     (rect.GetX(), rect.GetY(), rect.GetRight(), rect.GetBottom()))

    def overlap(a, b, gap=0.0):
        return (min(a[2], b[2]) - max(a[0], b[0]) + gap > 0
                and min(a[3], b[3]) - max(a[1], b[1]) + gap > 0)

    boxes = {ref: bounds(ref) for ref in PLACEMENT}
    errors = []
    for ref, box in boxes.items():
        if (box[0] < REGION[0] or box[1] < REGION[1]
                or box[2] > REGION[2] or box[3] > REGION[3]):
            errors.append(f"{ref} courtyard outside red zone: {box}")
        if overlap(box, TOP_NOTCH):
            errors.append(f"{ref} courtyard overlaps top board cutout: {box}")
    refs = list(boxes)
    for index, ref in enumerate(refs):
        for other in refs[index + 1:]:
            if overlap(boxes[ref], boxes[other], CLEARANCE):
                errors.append(f"{ref}/{other} courtyards overlap")
        for fixed in FIXED_REFERENCES:
            if overlap(boxes[ref], bounds(fixed), CLEARANCE):
                errors.append(f"{ref}/{fixed} courtyards overlap")
    if errors:
        raise AssertionError("Red-zone validation failed:\n" + "\n".join(errors))
    return boxes


def children(text):
    """Span-aware S-expression scanner; quotes and nested coordinates are safe."""
    depth, quoted, escaped, start = 0, False, False, 0
    for i, ch in enumerate(text):
        if quoted:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                quoted = False
        elif ch == '"':
            quoted = True
        elif ch == "(":
            depth += 1
            if depth == 2:
                start = i
        elif ch == ")":
            if depth == 2:
                yield start, i + 1, text[start:i + 1]
            depth -= 1
    if depth or quoted:
        raise ValueError("Unbalanced KiCad file")


def footprint_blocks(text):
    result = {}
    for start, end, block in children(text):
        if block.startswith("(footprint "):
            match = re.search(r'\(property "Reference" "([^"]+)"', block)
            if not match or match[1] in result:
                raise ValueError("Missing or duplicate footprint reference")
            result[match[1]] = (start, end, block)
    return result


def signature(board):
    return sorted((f.GetReference(), f.GetValue(), f.GetFPIDAsString(),
                   sorted((p.GetNumber(), p.GetNetname(),
                           p.GetDrillSize().x, p.GetDrillSize().y,
                           p.GetSize().x, p.GetSize().y) for p in f.Pads()))
                  for f in board.GetFootprints())


def xy(point):
    return (pcbnew.ToMM(point.x), pcbnew.ToMM(point.y))


def measurements(board):
    fp = {f.GetReference(): f for f in board.GetFootprints()}
    def p(ref, pin):
        return xy(next(p for p in fp[ref].Pads() if p.GetNumber() == pin).GetPosition())
    def distance(a, b):
        return math.dist(p(*a), p(*b))
    links = {
        "switch_to_diode": (("U3", "1"), ("D4", "2")),
        "diode_to_output_cap": (("D4", "1"), ("C8", "1")),
        "output_cap_to_switch_ground": (("C8", "2"), ("U3", "2")),
        "inductor_to_switch": (("L1", "2"), ("U3", "1")),
        "sense_to_pin7": (("R7", "2"), ("U3", "7")),
        "input_cap_to_vin": (("C6", "1"), ("U3", "6")),
        "input_cap_to_ground": (("C6", "2"), ("U3", "2")),
        "timing_to_pin3": (("C7", "1"), ("U3", "3")),
        "feedback_upper_to_pin5": (("R9", "2"), ("U3", "5")),
        "feedback_lower_to_pin5": (("R10", "1"), ("U3", "5")),
        "charge_cap_to_clamp": (("C9", "2"), ("D6", "2")),
        "charge_cap_to_rectifier": (("C9", "2"), ("D7", "2")),
        "switch_to_charge_cap": (("U3", "1"), ("C9", "1")),
    }
    return {name: round(distance(*link), 3) for name, link in links.items()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=BOARD)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    parser.add_argument("--placement-json", type=Path)
    args = parser.parse_args()
    if args.placement_json:
        overrides = json.loads(args.placement_json.read_text(encoding="utf-8"))
        if not overrides.keys() <= PLACEMENT.keys():
            raise ValueError("Unexpected reference in placement override")
        PLACEMENT.update(overrides)
    before_bytes = args.input.read_bytes()
    before = before_bytes.decode("utf-8")
    source = footprint_blocks(before)
    board = pcbnew.LoadBoard(str(args.input))
    before_signature = signature(board)
    before_measurements = measurements(board)
    fp = {f.GetReference(): f for f in board.GetFootprints()}
    if len(board.GetTracks()):
        raise ValueError("Placement-only input required; existing traces must be handled explicitly")
    if not set(PLACEMENT) <= fp.keys():
        raise ValueError("Missing target footprint")
    for ref, (x, y, angle) in PLACEMENT.items():
        item = fp[ref]
        item.SetOrientationDegrees(angle)
        item.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(x), pcbnew.FromMM(y)))
        # A rotated footprint's text orientation is global in pcbnew, not local.
        text = item.Reference()
        text.SetTextAngle(pcbnew.EDA_ANGLE(0, pcbnew.DEGREES_T))
        text.SetTextSize(pcbnew.VECTOR2I(pcbnew.FromMM(0.85), pcbnew.FromMM(0.85)))
        text.SetTextThickness(pcbnew.FromMM(0.13))
    place_reference_fields(board)
    # Legacy block-divider silk lines and off-board draft notes describe the old
    # placement. Retain them as editable drawing annotations, not printed silk.
    changed_graphics = set()
    note_index = 0
    for drawing in board.GetDrawings():
        if drawing.GetLayer() != pcbnew.F_SilkS:
            continue
        if isinstance(drawing, pcbnew.PCB_TEXT):
            drawing.SetLayer(pcbnew.Dwgs_User)
            drawing.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(50), pcbnew.FromMM(13 + 2*note_index)))
            drawing.SetTextAngle(pcbnew.EDA_ANGLE(0, pcbnew.DEGREES_T))
            drawing.SetTextSize(pcbnew.VECTOR2I(pcbnew.FromMM(0.6), pcbnew.FromMM(0.6)))
            note_index += 1
            changed_graphics.add(drawing.m_Uuid.AsString())
        elif isinstance(drawing, pcbnew.PCB_SHAPE):
            drawing.SetLayer(pcbnew.Dwgs_User)
            changed_graphics.add(drawing.m_Uuid.AsString())
    def graphic_id(block):
        if not re.match(r'\(gr_(?:text|line)\b', block):
            return None
        match = re.search(r'\(uuid "([^"]+)"\)', block)
        return match[1] if match else None
    if signature(board) != before_signature:
        raise AssertionError("Placement altered electrical or footprint identity")
    with tempfile.TemporaryDirectory(prefix="pico-power-place-") as tmp:
        normal = Path(tmp) / "native.kicad_pcb"
        pcbnew.SaveBoard(str(normal), board)
        native_text = normal.read_text(encoding="utf-8")
        # Match the input's newline convention without Windows text-mode
        # translation, which would turn retained CRLF into CRCRLF.
        if "\r\n" in before:
            native_text = native_text.replace("\n", "\r\n")
        generated = footprint_blocks(native_text)
    after = before
    replacements = []
    for ref in PLACEMENT:
        start, end, _ = source[ref]
        replacements.append((start, end, generated[ref][2]))
    native_graphics = {graphic_id(block): block for _, _, block in children(native_text)
                       if graphic_id(block) in changed_graphics}
    for start, end, block in children(before):
        if graphic_id(block) in changed_graphics:
            replacements.append((start, end, native_graphics[graphic_id(block)]))
    for start, end, replacement in sorted(replacements, reverse=True):
        after = after[:start] + replacement + after[end:]
    result = footprint_blocks(after)
    for ref in source.keys() - PLACEMENT.keys():
        if source[ref][2] != result[ref][2]:
            raise AssertionError(f"Unrelated footprint modified: {ref}")
    untouched_before = [b for _, _, b in children(before) if not b.startswith("(footprint ") and graphic_id(b) not in changed_graphics]
    untouched_after = [b for _, _, b in children(after) if not b.startswith("(footprint ") and graphic_id(b) not in changed_graphics]
    if untouched_before != untouched_after:
        raise AssertionError("Board drawing, track, zone or keepout was modified")
    if args.input.read_bytes() != before_bytes:
        raise RuntimeError("Input was edited during placement; refusing to overwrite")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(after.encode("utf-8"))
    reloaded = pcbnew.LoadBoard(str(args.output))
    if signature(reloaded) != before_signature:
        raise AssertionError("Reloaded PCB electrical signature mismatch")
    red_zone_bounds = validate_red_zone(reloaded)
    report = {
        "input_sha256": hashlib.sha256(before_bytes).hexdigest(),
        "footprints_moved": sorted(PLACEMENT),
        "electrical_signature_unchanged": True,
        "other_footprints_edges_keepouts_and_nets_verbatim": True,
        "all_target_courtyards_inside_red_zone": True,
        "target_courtyard_overlap_count": 0,
        "red_zone_mm": REGION,
        "top_board_cutout_mm": TOP_NOTCH,
        "target_courtyard_bounds_mm": red_zone_bounds,
        "draft_annotations_moved_to_Dwgs_User": len(changed_graphics),
        "before_pad_distances_mm": before_measurements,
        "after_pad_distances_mm": measurements(reloaded),
        "placements_mm_degrees": PLACEMENT,
        "note": "Distances are straight-line pad distances, not routed lengths or measured EMI.",
    }
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
