[target.thumbv8m.main-none-eabihf]
runner = "C:\\Users\\choco\\Documents\\scriptPath\\picotool\\picotool.exe load -u -v -x -t elf"
# runner = "elf2uf2-rs -s"
# runner = "probe-rs run --chip RP235x --protocol swd"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
