[package]
name = "pico2w-matter-probe"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[[bin]]
name = "pico2w-matter-probe"
path = "main.rs"
test = false
bench = false

[dependencies]
embassy-executor = "0.10"
embassy-rp = { version = "0.10", features = ["rp235xa", "time-driver", "critical-section-impl", "binary-info", "executor-thread", "executor-interrupt"] }
embassy-time = "0.5"
embassy-futures = "0.1"
embassy-usb-logger = "0.6"
embassy-usb = "0.6"
embassy-net = { version = "0.9.1", features = ["udp", "dhcpv4", "medium-ethernet", "proto-ipv4", "proto-ipv6", "multicast"] }
cyw43 = { version = "0.7", features = ["log"] }
cyw43-pio = "0.10"
cortex-m = { version = "0.7", features = ["inline-asm"] }
cortex-m-rt = "0.7"
static_cell = "2.1"
log = "0.4"
heapless = "0.9"
embedded-alloc = "0.7"
rand_chacha = { version = "0.10", default-features = false }
rand_core = "0.10"
rs-matter = { path = "../../.local/matter-probe/rs-matter/rs-matter", default-features = false, features = ["rustcrypto", "log", "max-fabrics-1", "max-sessions-3", "max-exchanges-per-session-3", "max-acls-per-fabric-1"] }

[build-dependencies]
toml = "0.9"
getrandom = "0.4"
verhoeff = "1"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
debug = 2
